### ISSUE TITLE
Bug: Problems installing?

### ISSUE THREAD

**Issue by moogah** [agzam/browser-hist.el#12]
I'm running emacs v28 on macos, using straight.el to manage packages.  This is my config:

```
(use-package sqlite
  :straight t)

(use-package browser-hist
  :straight (browser-hist :type git :host github :repo "agzam/browser-hist.el")
  :config
  (setq browser-hist-db-paths
        '(chrome . "$HOME/Library/Application\ Support/Google/Chrome/Default/History"))
 (setq browser-hist-default-browser 'chrome))
```

Which results in this backtrace:
```

> Debugger entered--Lisp error: (error "Loading file /Users/jefarr/.emacs.d/straight/build/browser-hist/browser-hist.elc failed to provide feature ‘browser-hist’")
>   require(browser-hist nil t)
>   (not (require 'browser-hist nil t))
>   (if (not (require 'browser-hist nil t)) (display-warning 'use-package (format "Cannot load %s" 'browser-hist) :error) (condition-case err (progn (setq browser-hist-db-paths '(chrome . "$HOME/Library/ApplicationSupport/Google/Chrome/Def...")) (setq browser-hist-default-browser 'chrome) t) ((debug error) (funcall use-package--warning62 :config err))))
>   (condition-case err (if (not (require 'browser-hist nil t)) (display-warning 'use-package (format "Cannot load %s" 'browser-hist) :error) (condition-case err (progn (setq browser-hist-db-paths '(chrome . "$HOME/Library/ApplicationSupport/Google/Chrome/Def...")) (setq browser-hist-default-browser 'chrome) t) ((debug error) (funcall use-package--warning62 :config err)))) ((debug error) (funcall use-package--warning62 :catch err)))
>   eval-buffer(#<buffer  *load*> nil "/Users/jefarr/.emacs.d/init.el" nil t)  ; Reading at buffer position 3643
>   load-with-code-conversion("/Users/jefarr/.emacs.d/init.el" "/Users/jefarr/.emacs.d/init.el" t t)
>   load("/Users/jefarr/.emacs.d/init" noerror nomessage)
>   startup--load-user-init-file(#f(compiled-function () #<bytecode -0x148feec25999a87>) #f(compiled-function () #<bytecode -0x1f3c686ddc0d6275>) t)
>   command-line()
>   normal-top-level()
```

**Comment by moogah** [comment]
This is probably just a result of the broken install, but in case it helps I can actually run `M-x browser-hist-search` but it results in an error which seems fairly late in the code path since I can see some of my most recent sites in the backtrace:

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   propertize(nil invisible t)
>   #f(compiled-function (x) #<bytecode 0x1f00bc14310d2ed>)(nil)
>   mapcar(#f(compiled-function (x) #<bytecode 0x1f00bc14310d2ed>) (nil ("https://github.com/agzam/browser-hist.el/issues" . "Issues · agzam/browser-hist.el · GitHub") ("https://github.com/agzam/browser-hist.el" . "GitHub - agzam/browser-hist.el: Search through bro...") ("https://www.google.com/search?q=emacs+browser-hist..." . "emacs browser-hist - Google Search") ("https://www.reddit.com/r/emacs/comments/ad3b36/how..." . "how to fix and prevent the following warning: mark...") ("https://www.google.com/search?q=failed+to+provide+..." . "failed to provide feature - Google Search") ("https://dev.cloud.jenkins.service.csnzoo.com/job/p..." . "17114 Console [Jenkins]") ("https://dev.cloud.jenkins.service.csnzoo.com/job/p..." . "packer-ondemand-builds [Jenkins]")))
>   #f(compiled-function #'sequence #<bytecode 0x1848f60a293f5574>)(#f(compiled-function (x) #<bytecode 0x1f00bc14310d2ed>) (nil ("https://github.com/agzam/browser-hist.el/issues" . "Issues · agzam/browser-hist.el · GitHub") ("https://github.com/agzam/browser-hist.el" . "GitHub - agzam/browser-hist.el: Search through bro...") ("https://www.google.com/search?q=emacs+browser-hist..." . "emacs browser-hist - Google Search") ("https://www.reddit.com/r/emacs/comments/ad3b36/how..." . "how to fix and prevent the following warning: mark...") ("https://www.google.com/search?q=failed+to+provide+..." . "failed to provide feature - Google Search") ("https://dev.cloud.jenkins.service.csnzoo.com/job/p..." . "17114 Console [Jenkins]") ("https://dev.cloud.jenkins.service.csnzoo.com/job/p..." . "packer-ondemand-builds [Jenkins]")))
>   apply(#f(compiled-function #'sequence #<bytecode 0x1848f60a293f5574>) #f(compiled-function (x) #<bytecode 0x1f00bc14310d2ed>) (nil ("https://github.com/agzam/browser-hist.el/issues" . "Issues · agzam/browser-hist.el · GitHub") ("https://github.com/agzam/browser-hist.el" . "GitHub - agzam/browser-hist.el: Search through bro...") ("https://www.google.com/search?q=emacs+browser-hist..." . "emacs browser-hist - Google Search") ("https://www.reddit.com/r/emacs/comments/ad3b36/how..." . "how to fix and prevent the following warning: mark...") ("https://www.google.com/search?q=failed+to+provide+..." . "failed to provide feature - Google Search") 
>   seq-map(#f(compiled-function (x) #<bytecode 0x1f00bc14310d2ed>) (nil ("https://github.com/agzam/browser-hist.el/issues" . "Issues · agzam/browser-hist.el · GitHub") ("https://github.com/agzam/browser-hist.el" . "GitHub - agzam/browser-hist.el: Search through bro...") ("https://www.google.com/search?q=emacs+browser-hist..." . "emacs browser-hist - Google Search") ("https://www.reddit.com/r/emacs/comments/ad3b36/how..." . "how to fix and prevent the following warning: mark...") ("https://www.google.com/search?q=failed+to+provide+..." . "failed to provide feature - Google Search") 
>   browser-hist-search()
>   funcall-interactively(browser-hist-search)
>   call-interactively(browser-hist-search record nil)
>   command-execute(browser-hist-search record)
>   execute-extended-command(nil "browser-hist-search" nil)
>   funcall-interactively(execute-extended-command nil "browser-hist-search" nil)
>   call-interactively(execute-extended-command nil nil)
>   command-execute(execute-extended-command)

**Comment by agzam** [comment]
I am closing this matter as it feels no longer relevant or actionable due to its age.
