### ISSUE TITLE
Error for Invalid SQL query on Mac and Safari

### ISSUE THREAD

**Issue by jayrajput** [agzam/browser-hist.el#17]
Folllowing error can be seen when running `browser-hist.el` with safari.

    Error in post-command-hook (vertico--exhibit): (sqlite-error ("SQL logic error" "near \"i\": syntax error" 1 1))

Configuration Setting

    (use-package browser-hist
    :load-path "~/git/browser-hist.el"
    :init
    (setq browser-hist-default-browser 'safari)
    (setq browser-hist-cache-timeout 60))

SQL query can be seen as a culprit

    SELECT DISTINCT v.title, i.url FROM history_items  WHERE ( title IS NOT NULL AND TITLE <> ’’ ) i JOIN history_visits v ON i.id = v.history_item ORDER BY v.visit_time desc LIMIT 100

The fix is to update the variable. I can send a PR, if it is OK with you.

    modified   browser-hist.el
    @@ -96,8 +96,7 @@
         (chromium "title"   "url"   "urls"          "ORDER BY last_visit_time desc")
         (brave    "title"   "url"   "urls"          "ORDER BY last_visit_time desc")
         (firefox  "title"   "url"   "moz_places"    "ORDER BY last_visit_date desc")
    -    (safari   "v.title" "i.url" "history_items"
    -     "i JOIN history_visits v ON i.id = v.history_item ORDER BY v.visit_time desc")))
    +    (safari   "v.title" "i.url" "history_items i JOIN history_visits v ON i.id = v.history_item"  "ORDER BY v.visit_time desc")))

**Comment by agzam** [comment]
Yes, PRs are always welcome. Unfortunately, atm I don't have access to a Mac machine, I can't fix that with confidence.

**Comment by jayrajput** [comment]
I have sent a PR request after verifying the fix on my Mac + Safari environment.
