### ISSUE TITLE
Feature: Add Safari

### ISSUE THREAD

**Issue by agzam** [agzam/browser-hist.el#5]
I personally don't use Safari, but many people do. It should be added.

**Comment by suliveevil** [comment]
This Alfred Workflow is awesome, it read Safari history from sqlite file.
https://github.com/al3rez/sh

`{query}`

```shell
cp ~/Library/Safari/History.db /tmp/h && sqlite3 /tmp/h "select json_object('items', json_group_array(json_object('quicklookurl', url, 'uid', title, 'title', title, 'arg', url))) as json_result from (select v.title, i.url, i.visit_count_score from history_items i join history_visits v on (v.history_item = i.id and v.title LIKE '%{query}%') group by v.title)"
```

**Comment by suliveevil** [comment]
Chrome counterpart:

https://github.com/al3rez/ch

```shell
cp -f ~/Library/Application\ Support/Google/Chrome/Default/History /tmp/ch
sqlite3 /tmp/ch "select json_object('items', json_group_array(json_object('quicklookurl', url, 'uid', title, 'title', title, 'arg', url))) as json_result from (SELECT url, title, visit_count FROM urls WHERE title LIKE '%{query}%' ORDER BY visit_count)"
```

**Comment by agzam** [comment]
added in:
https://github.com/agzam/browser-hist.el/commit/3f4da5b08a8c40d6a1d6874cbe078768564b43fb

**Comment by suliveevil** [comment]
You are my hero!

**Comment by agzam** [comment]
> You are my hero!

Gee, thanks. It wasn't much work. I hope the package works for you as is. I just realized it only works in Emacs 29. I'll find time later to make it compatible with older versions.
