### ISSUE TITLE
Only works in Emacs 29

### ISSUE THREAD

**Issue by tillydray** [agzam/browser-hist.el#9]
When I type `M-x browser-hist`, nothing comes up. I followed the instructions a couple of times to make sure I wasn't missing something. I'm using

- GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.1.0, Carbon Version 169 AppKit 2299)
- latest Doom Emacs
  - Doom core     v3.0.0-pre       HEAD -> master d5ccac5d 2022-12-02 00:36:06 +0100
  - Doom modules  v22.10.0-pre     HEAD -> master d5ccac5d 2022-12-02 00:36:06 +0100
- macos 13.0.1 (22A400)

### example literate config file

```emacs-lisp
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
(package! browser-hist :recipe (:host github :repo "agzam/browser-hist.el"))
#+end_src

#+begin_src emacs-lisp :tangle ~/.doom.d/config.el
(setq browser-hist-db-paths
      '((firefox . "$HOME/Library/Application Support/Firefox/Profiles/sklu6cvu.default-release/places.sqlite")))

(setq browser-hist-default-browser 'firefox)
#+end_src
```

### Proof my sqlite database is there

```sh
$ if test -f "$HOME/Library/Application Support/Firefox/Profiles/sklu6cvu.default-release/places.sqlite"; then echo "yes"; fi
yes
```

### proof browser-hist.el is installed

I'm a bit of an emacs noob so maybe this isn't actual proof? I don't know

```sh
$ pwd && ls | grep browser
/Users/jason/.emacs.d/.local/straight/repos
browser-hist.el
```

**Comment by agzam** [comment]
I appreciate your feedback and I'm very sorry it didn't work for you. I should've tested it more before putting it out. It's most likely can't find the db file.

I'm trying to revamp the path finder mechanism, give me a couple of days, I'll try to fix it.

**Comment by agzam** [comment]
It looks like you're missing `use-package!` block, e.g., :

```
(use-package! browser-hist
  :init
  (require 'embark)
  :commands (browser-hist-search)
  :config
  (setq browser-hist-db-paths
      '((firefox . "$HOME/Library/Application Support/Firefox/Profiles/sklu6cvu.default-release/places.sqlite"))
    browser-hist-default-browser 'firefox))
```

**Comment by JasonMFry** [comment]
Thanks for the reply, and for trying to help! I added the `use-package!` block, did `M-x toggle-debug-on-error`, then got this output. Notice it says Brave and not Firefox 😕 

```elisp
Debugger entered--Lisp error: (void-function sqlite-open)
  sqlite-open("/var/folders/mf/m0cjmt190cbbhd_tvk4lw8pc0000gn/T/bhist-brave.sqlite")
  browser-hist--query(brave)
  browser-hist-search()
  funcall-interactively(browser-hist-search)
  command-execute(browser-hist-search record)
  counsel-M-x-action("browser-hist-search")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "browser-hist-search" "tide-restart-server" "tide-jsdoc-template" "tide-mode" "tide-setup" "query-replace" "package-install" "lsp-mode" "lsp-install-server" "lsp" "man" "magit-revert-and-commit" "nov-mode" "vc-revert" "sql-sqlite" "tags-search" "doom/version" "company-tabnine" "lisp-eval-defun" "npm-mode" "nodejs-repl" "tide-format" "list-packages" "pdf-view-mode" "bundle-install" "haskell-compile" "lsp-describe-session" "pdf-virtual-view-mode" "lsp-workspace-folders-add" "lsp-workspace-folders-remove" "company-tabnine-install-binary" "centaur-tabs--copy-file-name-to-clipboard" "eww" "lsp!" "woman" "find-tag" "html-mode" "json-mode" "list-tags" "magit-log" "lsp-rename" "run-haskell" "haskell-menu" "inferior-lisp" "markdown-open" "pdf-tools-help" "org-timestamp-up" "magit-cherry-pick" "pdf-tools-install" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)
```

Here are the relevant bits of my literate config. I added `embark`, I wasn't aware that was a dependency for your package
```elisp
#+begin_src emacs-lisp :tangle ~/.doom.d/packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
(package! browser-hist :recipe (:host github :repo "agzam/browser-hist.el"))
(package! embark)
#+end_src

#+begin_src emacs-lisp :tangle ~/.doom.d/config.el
(use-package! browser-hist
  :init (require 'embark)
  :commands (browser-hist-search)
  :config (setq browser-hist-db-paths
                '((firefox . "$HOME/Library/Application Support/Firefox/Profiles/sklu6cvu.default-release/places.sqlite")) browser-hist-default-browser 'firefox))
#+end_src
```

I have no idea what's going on 😕

**Comment by agzam** [comment]
Hmm. what's the version of Emacs you have? Can you eval `(sqlite-available-p)` and see what it says? Maybe your instance got built without sqlite support?

**Comment by JasonMFry** [comment]
GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.1.0, Carbon Version 169 AppKit 2299)

I did `M-: (sqlite-available-p)` and got `Symbol’s function definition is void: sqlite-available-p`. But I can do `M-x sql-sqlite` and point it to my Firefox sqlite database. Does that indicate I do or do not have sqlite support? But when I do `describe-function` or `describe-variable` and search for `sqlite` there are only 14 and 16 results, which is very very few

**Comment by agzam** [comment]
Damn, it looks like sqlite support was added only in 29.1. For some reason I thought it was added earlier. I'm gonna have to make some changes for backward compatibility.

**Comment by JasonMFry** [comment]
I was about to upgrade to 29 because why not, but [Doom Emacs' prereqs](https://github.com/doomemacs/doomemacs/#prerequisites) specifically say

> Emacs 27.1+ (28.1 is recommended, or native-comp. 29+ is not supported).

Melpa has the following and I tried to install each of them and evaluate `(sqlite-available-p)` but it still didn't work :shrug:

- sqlite3
- sqlite
- esqlite
- emacsql-sqlite3
- emacsql-sqlite

sent via email

**Comment by agzam** [comment]
Although I've been happily using 29 for months now, I wouldn't suggest upgrading for a single package that may not even work :) 

I'll try to figure out the backward compatibility soon.

**Comment by JasonMFry** [comment]
🤷🏼 it's easy enough for me to rollback
